services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rbac
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://postgres:1234@db:5432/rbac?schema=public
      JWT_SECRET: change-this-secret-in-production
      DOTENV_CONFIG_PATH: ""
      DISABLE_HELMET: "true"

  seed:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/rbac?schema=public
      DOTENV_CONFIG_PATH: ""
    command: sh -c "npx prisma migrate deploy && npx tsx prisma/seed.ts"
    restart: "no"

volumes:
  pgdata:
